### ISSUE TITLE
Lots of domains

### ISSUE THREAD

**Issue by kamikazechaser** [ivolo/disposable-email-domains#134]
Some temp email providers seem to be generating random emails from potentially hundreds of domains that they have access to. Would it be viable to try and blacklist them?

~~An example is temp-email~~ (Just checked they have access to like 10 domains)

**Comment by GeroldSetz** [comment]
We do that already at bdea.cc 😀

Yes, it is worth it...

Gerold

Am 17.06.2017 13:34 schrieb "Mohammed Sohail" <notifications@github.com>:

**Comment by kamikazechaser** [comment]
Great, cause a lot of domains can be acquired free of charge these days.
