### ISSUE TITLE
what are the forks for?

### ISSUE THREAD

**Issue by schucan** [ivolo/disposable-email-domains#18]
Hello Daniel

Why are there two forks of this list (this one and danhstevens/disposable-email-domains)? They seem to both be maintained by you.

Thanks, and cheers,
Luzi.

**Comment by danhstevens** [comment]
Hey Luzi,

I maintained my own fork before ivolo added me as a contributor here :)

Cheers,
Dan

**Comment by schucan** [comment]
Thanks Daniel. Then please indicate that on your own fork - or remove it.

Is there a way I can contact you privately?

**Comment by danhstevens** [comment]
Not sure what you mean. There are currently 22 forks of this repository. Forking is a standard Github workflow. Maybe I'm missing what you're asking.

**Comment by schucan** [comment]
Sorry, Daniel. I didn't see the other forks.

I know about forking in general. As for this specific repository: it seems
obvious to me to use just one single list of disposable email domains -
since we are all using the same internet, right?

Do you see a way all these forks could be brought together?

What are your thoughts on this?

I don't know if an issue is the right channel for this discussion....

Cheers,
Luzi.
