### ISSUE TITLE
emailondeck.com alternative domains

### ISSUE THREAD

**Issue by GeroldSetz** [ivolo/disposable-email-domains#213]
Hi Ilya,
these domains are hard to catch, I know, I know. That's why I decided to share data in plaintext from www.block-disposable-email.com for this specific dea provider. Feel free to integrate it: https://github.com/GeroldSetz/emailondeck.com-domains

Would be great to get a link from your README.

Gerold

**Comment by tompec** [comment]
Thanks @GeroldSetz, I've included that in my last PR.

**Comment by danhstevens** [comment]
and pulled. Thanks fellas!
