### ISSUE TITLE
Composer installation not available

### ISSUE THREAD

**Issue by eusonlito** [ivolo/disposable-email-domains#232]
You have a `composer.json` file but the package is not registered at https://packagist.org/ then can not be installed with `composer require ivolo/disposable-email-domains`:

```
$ composer require ivolo/disposable-email-domains
                                                                                                                                                                
  [InvalidArgumentException]                                                                                                                                      
  Could not find package ivolo/disposable-email-domains at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
```

Regards!

**Comment by kamikazechaser** [comment]
As you say, its not listed on Packagist, however [here](https://github.com/mariomka/disposable-email-detector) is a php package based on this library.

**Comment by brolaugh** [comment]
Shouldn't this issue be closed as it hasn't gotten any action since Oct 13th 2017?

**Comment by eusonlito** [comment]
Yes, I'm currently using my own package https://github.com/eusonlito/disposable-email-validator

**Comment by danhstevens** [comment]
I've also added it here: https://packagist.org/packages/ivolo/disposable-email-domains

Sorry for the slow response on this one!
