### ISSUE TITLE
Every month Releases

### ISSUE THREAD

**Issue by fizerkhan** [ivolo/disposable-email-domains#262]
I saw that the "index.json" is getting updated regularly.  But release is not there to update the package. So I have to wait for a new release.

It will be great if you make release on 1st and 15th every month. What do you think about it?

**Comment by danhstevens** [comment]
Sounds good. I'll do my best to push a release on the 1st and 15th.

**Comment by fizerkhan** [comment]
@danhstevens Awesome. Thank you so much. 👍
