### ISSUE TITLE
No more disposable domains policy

### ISSUE THREAD

**Issue by bago** [ivolo/disposable-email-domains#271]
What's your policy with domains that are no more used for DEA services?

Most domains in the list don't even have an MX or A record or they don't exists anymore or they don't provide any nameserver, so they can't anymore be disposable email address. At most, they are dead addresses.

Some other domain is alive, but I'm mosty sure they have been disposable years ago and they are now not anymore disposable.

So, my question: are these domains listed "by design" or are they listed "by mistake"?

**Comment by danhstevens** [comment]
Hey @bago - good question. First, most of these domains **do** still have valid MX records - over 70% as of this morning. And that's not counting those that have no MX records but have A records instead. Nonetheless, some of these domains are probably no longer active but are kept on this list for those looking to identify disposable domains from older data sets. To date, we've had no known "good" email domains that were previously used as a disposable domain. If that day comes the owner of the domain can simply create a GitHub issue and we'll take a look and remove if necessary. Hope that helps!

**Comment by bago** [comment]
OK, so it is "by design".

About the ex-DEA, now legitimate I think "suzukilab.net" is one of them... but there may be other... It is hard to really be sure when a domain is not used anymore as DEA. BTW in the context of cleaning, you probably want to list them anyway as if you have a suzukilab.net email address in an old list, then it was probably from the disposable era.

**Comment by danhstevens** [comment]
I see `mx1.mytemp.email` in `suzukilab.net` MX records (lower priority) so whatever that domain is up to, it's still not all good :)

**Comment by bago** [comment]
lower priority records are never used if the higher priority works.
That's the whole point of some spamtrap system like tarbaby.junkemailfilter.com ...

That's said.. your list, your choices... :-)

Here is a list of major freemail providers domain I found in your list and AFAIK has never been disposable:

> ukr.net, poczta.onet.pl, bigmir.net, sohu.com are domains for country-specific freemail providers
> qq.com, 21cn.com, yeah.net are domains for major chinese providers
> mail15.com, pisem.net, fromru.com are domains from the qip.ru provider

Of course freemail may be used for bad like disposable: the bad thing is not the "disposability" but being anonymouse or easily abusable (gmail.com and mail.ru are not disposable but are in the top 3 places for  https://www.stopforumspam.com/stats abuses).
