### ISSUE TITLE
Both wildcard and exact

### ISSUE THREAD

**Issue by rightaway** [ivolo/disposable-email-domains#279]
If a domain is both wildcard and exact, for example it allows addresses like `mail@example.com` and `mail@subdomain.example.com`, must it appear in both `index.json` and `wildcard.json`, or must it be only in `wildcard.json`?

**Comment by danhstevens** [comment]
Hi @rightaway - we put the parent of any wildcard domain in both index.json and wildcard.json. So, `*.example.com` should go in both files as `example.com`.
