### ISSUE TITLE
Free requests validation

### ISSUE THREAD

**Issue by topilski** [ivolo/disposable-email-domains#304]
Hi , do you have some limits for GET requests on url https://open.kickbox.com/v1/disposable/{DomainOrEmailAddress}  ?

**Comment by danhstevens** [comment]
We don’t have any established limits since it’s a simple lookup that scales nicely. Are you encountering any limits or just asking to determine if this approach will work for you?

**Comment by topilski** [comment]
I want to integrate some api into my sites, i tired cleanup my DB from fake emails.

**Comment by topilski** [comment]
Can you describe, how i can integrate your api into my site based on node.js ?

**Comment by danhstevens** [comment]
Great. The open api should work just fine for that.

**Comment by danhstevens** [comment]
You could call the api on the front or backend. If you do it in node I’d recommend using an npm like `request` to make a simple GET request.

**Comment by topilski** [comment]
Ok, i will try thank you!
