### ISSUE TITLE
New disposable domain candidate

### ISSUE THREAD

**Issue by topilski** [ivolo/disposable-email-domains#319]
Hi, please ban this domain: 10minut.com.pl

**Comment by danhstevens** [comment]
Fixed via 2d4aa3b500503abdc1881fe48afc7d0a9bdd16bd. Thanks!

**Comment by topilski** [comment]
Hi, please check this domain too: itis0k.org

**Comment by danhstevens** [comment]
Doesn't appear to have any mx records.
