### ISSUE TITLE
List the free email providers in free-email-domains

### ISSUE THREAD

**Issue by cdman** [ivolo/disposable-email-domains#336]
Given that there is a gray zone between free and disposable email domains, I created a separate list for free email domains: https://gitlab.com/synappio/free-email-domains

You might want to redirect people asking for free (but not disposable) emails to be listed here (as do I in the reverse direction for disposable emails).

Cheers!

**Comment by danhstevens** [comment]
Much appreciated! I'll be sure to refer to this list for any future domains that should be categorized as free. If you see anymore free domains in this list, just let me know!
