### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by flayspammers** [ivolo/disposable-email-domains#365]
So you won't allow signup from a disposable email address service?  

oh noes!

What will I do?

Gee, maybe I'll treat a non-listed email service as disposable.

And why would I do that?

BECAUSE

the kind of cretinous fops who blacklist self-protection services are typically the scum bent on spamming me - a behavior I will vociferously resist.

YOU FAIL

This policy is INANITY

**Comment by danhstevens** [comment]
I don't know what you're trying to say. Is there a specific non-disposable domain listed you would like me to address? If you have a specific request, make it.
