### ISSUE TITLE
poczta.onet.pl

### ISSUE THREAD

**Issue by kdybicz** [ivolo/disposable-email-domains#42]
Hey,

I've just started using your list. It's great, thanks! But... there is at least one false-positive: poczta.onet.pl.
onet.pl is polish news site, and poczta.onet.pl is just regular free email service, but it's not the disposable-kind of free. It's often used by regular users, so would be nice if you could remove it from that list.

**Comment by danhstevens** [comment]
All fixed - thanks for pointing that out!
