### ISSUE TITLE
Not disposable hosts range in index.json

### ISSUE THREAD

**Issue by dmytrohoi** [ivolo/disposable-email-domains#460]
Hi!

I see in you base domain named by `pp.ua`, but this address reserved for PrivatePeople.Ukraine - free domain for Ukraine private persons (citizens) and will creating sub-domen, like my - hoi.pp.ua, for every approved by mobile number ukrainians.

I try add MX records for my domain, but every big mail-services call his: `550 Disposable email addresses are not permitted`.

Please, help me for fix that. (In MX I use [forwarde-mail](https://forwardemail.net/) )

**Comment by danhstevens** [comment]
Thanks for pointing that out! I've pushed a fix and rolled them up to our servers to pick up shortly.
