### ISSUE TITLE
remove non working domains

### ISSUE THREAD

**Issue by mderazon** [ivolo/disposable-email-domains#48]
Do you think it would be good to run tests for domain mx validity on the list and remove invalid domains ?

I can send a PR for such test then we can use a build server to check run it.

**Comment by mderazon** [comment]
something like this:

![screen shot 2016-09-08 at 3 08 59 pm](https://cloud.githubusercontent.com/assets/717076/18348809/3fa7c844-75d6-11e6-94bb-b4aba7ceb528.png)

**Comment by simonepri** [comment]
What if a domain is temporary down?

**Comment by rocboronat** [comment]
I think this issue is not a good idea :·)

**Comment by mderazon** [comment]
agree, closing

**Comment by rocboronat** [comment]
How fast! :·) Thank you, @mderazon ! :·)
