### ISSUE TITLE
Are there any disposable domains that we should NOT consider wildcard domains?

### ISSUE THREAD

**Issue by Taytay** [ivolo/disposable-email-domains#480]
There are wildcard domains called out explicitly in the wildcard domains, but I am having a hard time imagining a circumstance in which a domain listed in the main `index.json` should NOT also be considered a wildcard domain. 

If they are in fact separate lists, wouldn't that imply that a disposable provider listed in index.json like `fakemailz.com` would be considered to be a disposable address only if the email looks like `fake@fakemailz.com`, but NOT if it was `fake@somesubdomain.fakemailz.com`, right? Are there known scenarios where these TLDs are valid if there is indeed a new subdomain present?

**Comment by danhstevens** [comment]
Great question. There are likely _some_ instances where treating all disposable domains as wildcards could generate a false-positive, but I would imagine these would be quite rare. In your example, `somesubdomain.fakemailz.com` doesn't have an MX record and doesn't listen on port 25 so in the purest sense it's not a disposable email address - it's a non-existent email address. That said, by rejecting `*.fakemailz.com` you've accomplished your mission nonetheless. So, depending on your application, treating all domains as a wildcard may prove useful. If you take that route, let me know how it goes!
