### ISSUE TITLE
Push tags to GitHub?

### ISSUE THREAD

**Issue by jzaefferer** [ivolo/disposable-email-domains#50]
The newest release here https://github.com/ivolo/disposable-email-domains/releases 1.0.4.

While npm knows about up to 1.0.9. Better this way than the other way around, but would still be good to keep in sync.

PS: Thanks for this module, we just got started filtering these by hand...

**Comment by jzaefferer** [comment]
PS: Edited the original description. There's still the gap from 1.0.4 (GitHub) to 1.0.9 (npm).

**Comment by danhstevens** [comment]
Sounds good. Github only allows tagging of 'recent commits' so moving forward I'll make sure new tags are pushed with each release. Will keep this issue open until I push the next release.

Cheers!

**Comment by jzaefferer** [comment]
The last release on npm is now 3 months old, the last release on GitHub even older. Can you please tag and publish changes as you land them? Commits to master aren't that useful by themselves.

**Comment by jzaefferer** [comment]
Btw. `npm version patch` and its variations make this a lot easier. Updates `package.json`, commits that change and tags it.

**Comment by danhstevens** [comment]
1.0.10 has been published and tagged. Thanks for the nudge on this. I'll be adding tests shortly and doing more frequent publishes/tags.
