### ISSUE TITLE
Composer/Packagist dev-master

### ISSUE THREAD

**Issue by arsonik** [ivolo/disposable-email-domains#535]
Hello, 

First ! Congrats for the amazing work done ;)

Is their a hook missing between GitHub > Packagist to maintain the dev-master up to date ?
https://packagist.org/packages/ivolo/disposable-email-domains#dev-master
As I am writing the last commit on packagist is from 2019-04-03 22:17 UTC.

Cheers

**Comment by danhstevens** [comment]
Hello! I think there can sometimes be a delay for when packagist updates but it should be working. Just let me know if you still see any issue.
