### ISSUE TITLE
List contains domain without a valid TLD

### ISSUE THREAD

**Issue by brendanw** [ivolo/disposable-email-domains#671]
"xn--90abvrccwbp.xn--p1acf"

.xn-p1acf is not a valid TLD. I suggest only including domains with valid TLD's on the list.

**Comment by danhstevens** [comment]
Hi @brendanw! `xn--p1acf` is a valid TLD (https://www.iana.org/domains/root/db/xn--p1acf.html) and `xn--90abvrccwbp.xn--p1acf` is a real domain. Domains like these are notations for foreign character support.

**Comment by brendanw** [comment]
My bad! Thanks for the prompt reply and explanation. Much appreciated.
