### ISSUE TITLE
Luxus

### ISSUE THREAD

**Issue by nunoperalta** [ivolo/disposable-email-domains#677]
More to add: https://www.luxusmail.org/

@luxusmail.gq
@bitchmail.ga
@bitchmail.ga
@onedaymail.ga
@linuxmail.tk
@10minute.cf
@onedaymail.cf
@luxusmail.tk
@luxusmail.uk

**Comment by joanliu** [comment]
@danhstevens - I added some of these domains today, but looks like they rotated some out since this was opened. should these be added?

**Comment by nunoperalta** [comment]
When I open the page, the exact same list of emails appear to me. Maybe depends on the country?

**Comment by joanliu** [comment]
@nunoperalta I don't own this list of disposable domains - I just submit PRs to include domains I have verified are disposable. Dan is able to verify domains are disposable, so that's why I tagged him. If you're able to verify them, I'm sure Dan would accept your PR.

**Comment by danhstevens** [comment]
Added via 935bfbde73a5d72fb275350b749aeb71fa8c000d
Thanks!
