### ISSUE TITLE
remove sneakemail.com snkmail.com snkml.com

### ISSUE THREAD

**Issue by moi-virtual** [ivolo/disposable-email-domains#684]
sneakemail.com is a service I pay for. It will create alias or virtual email addresses. These are security aids. For example, if I get an email that looks like it's from thingamajig.com but really isn't, I can know that by the email address that the bogus message was sent to. Also, I was one of the first to tell aweber that their lists had been hacked because I started getting spam emails to addresses given only to aweber customers. The same thing happened with another Email Service Provider like aweber.

**Comment by danhstevens** [comment]
Thanks for your submission. I utilize disposable domain services to protect my privacy and discover who's sharing my info as well. This is just a list of disposable domains and sneakemail meets that definition - and advertise themselves as such. If a website is using this list to block a domain you believe they shouldn't block I recommend contacting them.

![image](https://user-images.githubusercontent.com/1061040/73099734-b250e180-3eb1-11ea-928a-42e566bd62a6.png)
