### ISSUE TITLE
Schedule releases more often

### ISSUE THREAD

**Issue by tamtamchik** [ivolo/disposable-email-domains#710]
At our service, we got a bunch of registrations from domains that were already added to the master branch since the last release. Can you please schedule new releases more often (maybe #650 can help with this) to have new domains published as soon as possible?

For now, I had to switch to using API for the most accurate version, but this is +1 request to third party service that if possible better to omit and use local list.

**Comment by danhstevens** [comment]
will do - just published 1.0.49
