### ISSUE TITLE
Consider blacklisting all freenom TLDs

### ISSUE THREAD

**Issue by hwvs** [ivolo/disposable-email-domains#728]
Freenom TLDs are heavily abused by spammers, are blocked by most spam filters and aren't used by any legitimate email providers that I know of. 53.02% of the index.json blacklist is made up of freenom domains.

TLDs:
```
.TK
.ML
.GA
.CF
.GQ
```

**Comment by danhstevens** [comment]
Thanks for the suggestion. Website operators might, at their discretion, add a regex that looks for those TLDs and dismiss them at their discretion. However, it would be a bit heavy handed to list at the TLD level as I'm sure there are _some_ legitimate users in there as well (however sparse).
