### ISSUE TITLE
Add lists from mail-temp.com

### ISSUE THREAD

**Issue by JaneJeon** [ivolo/disposable-email-domains#758]
So I noticed that email-temp.com was on your list (which redirected to mail-temp.com) but the temp domains from that site were not on this list (both index and wildcard)!

Example: totalmanpower.kiwi

Obviously this is just one domain but I think this could be a starting point for reeling in a whole slew of throwaway mail domains.

P.S. you can actually safely remove `index.js` and `wildcard.js`, because when you `require('.')` or `require('./index')`, if `index.js` is not there node will actually fall back to `require('./index.json')`. The same goes for `require('./wildcard')` - it will import `wildcard.json`.

**Comment by danhstevens** [comment]
Thanks @JaneJeon - We've added many of the mail-temp.com domains now. Let me know if you see anything else we can improve on!
