### ISSUE TITLE
Add 2 domains

### ISSUE THREAD

**Issue by ihejazi** [ivolo/disposable-email-domains#807]
Please add the following disposable domains:
johnderasia.com
officemalaga.com

Proofs:
https://pasteboard.co/J3CsYoi.png
https://prnt.sc/ryfm9n

Provider:
https://temp-mail.org/en/

**Comment by ihejazi** [comment]
Hi.
Here is another disposable email from temp-mail:
hubopss.com

Please also add it.

**Comment by ihejazi** [comment]
Hi.
Here is another disposable email from temp-mail:
govdep5012.com

Please also add it.

**Comment by danhstevens** [comment]
Fixed via 8bc0b9265551394b425901907ab6bcd040060bc6 - thanks!
