### ISSUE TITLE
Source and type of "beautycentry.xyz"

### ISSUE THREAD

**Issue by GeroldSetz** [ivolo/disposable-email-domains#844]
Hi,
I was trying to find the source for the domain "beautycentry.xyz". The assigned MX is mail.h-email.net which looks more like a domain parking service rather than a disposable email service. What was your reason to put it onto the blacklist?
Gerold

**Comment by tompec** [comment]
It comes from generator.email.
MX records on 2020-01-06 03:20:30 UTC were:
```
"hostname":"generator.email"
"ip":"51.38.115.65"
```

**Comment by GeroldSetz** [comment]
Perfect, thx.
