### ISSUE TITLE
add this domains.

### ISSUE THREAD

**Issue by sleepless-se** [ivolo/disposable-email-domains#853]
Please add this domains.

- 1-ml.com
- rmomail.com
- yosemail.com

**Comment by GeroldSetz** [comment]
source: https://temp-mail.org/en/

**Comment by tompec** [comment]
I've added `rmomail.com` & `yosemail.com` through https://github.com/ivolo/disposable-email-domains/pull/854

**Comment by danhstevens** [comment]
Merged. Thanks!
