### ISSUE TITLE
Add just4fun and aranelab

### ISSUE THREAD

**Issue by Paxamime** [ivolo/disposable-email-domains#876]
(REMOVED)

**Comment by Paxamime** [comment]
Also these domains:

mhzayt.online
cloudlinks.me
tortenboxer.de

**Comment by tompec** [comment]
@Paxamime please mention where these domains are coming from to help verifying them. Thanks.

**Comment by Paxamime** [comment]
These are primarily from tech support scammers that spam our site and are not yet within the list of disposable domains. I do validate for each domain if they are disposable prior to sharing them here. What is the best way to share the details that you need? This particular bot/user generally spams with the first name of Edword and then a variation of last names such as William, Davis, Diaz, etc., all with numbers added on to the end of it. They then cycle through a large amount of various disposable emails, some of which are missing from this list. 

"Edword William788",
"(redacted)@yektara.com"

"Edword William47",
"(redacted)@ofdow.com"
        
"Edword William76",
"(redacted)@nedoz.com"
      
"Edword William23",
"(redacted)@btsese.com"

"Edword William21",
"(redacted)@dkt1.com"

"Edword William13",
"(redacted)@5y5u.com"

"Edword William92",
"(redacted)@ofdow.com"

"Edword William311",
"(redacted)@nedoz.com"

"Edword William58",
"(redacted)@nedoz.com"

"Edword William566",
"(redacted)@aranelab.com"

**Comment by Paxamime** [comment]
Additional addresses:

avmtk.com
dashseat.com
eamarian.com
loopsnow.com
nedoz.com
pashter.com
serohiv.com
1adir.com
aiclbd.com
