### ISSUE TITLE
Add wwdee.com

### ISSUE THREAD

**Issue by m00tt** [ivolo/disposable-email-domains#927]
Please add "wwdee.com".
Reference here: https://temp-mail.org/it/
![disposable](https://user-images.githubusercontent.com/74110459/147857760-e305ce0f-a928-4692-99f3-da175efdb7f4.PNG)

**Comment by m00tt** [comment]
Add also:  xxyxi.com
(from same website)

**Comment by m00tt** [comment]
Add also: zherben.com

**Comment by m00tt** [comment]
Add also: zoeyy.com

**Comment by tompec** [comment]
All added in https://github.com/ivolo/disposable-email-domains/pull/926

**Comment by m00tt** [comment]
Optimal! but why then is the list for node.js not updated?
Do I have to reinstall the library every time an update is done on your part?

**Comment by m00tt** [comment]
Optimal!

Following are missing:
 - rezunz.com
 - rubygon.com
 - unigeol.com

**Comment by BenHarris** [comment]
A few more from temp mail:

- upsdom.com
- whecode.com
- wusehe.com

**Comment by tompec** [comment]
All done! https://github.com/ivolo/disposable-email-domains/pull/928

**Comment by danhstevens** [comment]
thanks @tompec !
